spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/activityaifitness
      database: activityaifitness

  kafka:
    bootstrap-server: localhost:9092
    producer:
      key-serializer: 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9101
