spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/ai-fitnessdb-userms
    username: postgres
    password: Chhitize@123

  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9100

app:
  name: Fitness AI
  version: 1.0.0
